### ISSUE TITLE
Segfault in oguri_next_buffer

### ISSUE THREAD

**Issue by vilhalmer** [vilhalmer/oguri#7]
There appears to be a code path somewhere that doesn't initialize the wl_list of buffers on an output:
```
Core was generated by `/home/vil/Code/oguri/build/oguri -s 0 /home/vil/.config/wallpaper fill'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fc5b7be88e0 in wl_list_insert () from /usr/lib/libwayland-client.so.0
(gdb) back
#0  0x00007fc5b7be88e0 in wl_list_insert () at /usr/lib/libwayland-client.so.0
#1  0x000055ac33a2b1f7 in oguri_next_buffer (output=0x55ac33bd0080) at ../buffers.c:99
#2  0x000055ac33a2a9c5 in oguri_render_frame (anim=0x55ac33bc4b90) at ../animation.c:103
#3  0x000055ac33a2bc58 in main (argc=5, argv=0x7ffe2f72bbf8) at ../oguri.c:250
(gdb) frame 2
#2  0x000055ac33a2a9c5 in oguri_render_frame (anim=0x55ac33bc4b90) at ../animation.c:103
warning: Source file is more recent than executable.
103			struct oguri_buffer * buffer = oguri_next_buffer(output);
(gdb) info locals
buffer = 0x0
image = 0x55ac33be1640
first_cycle = true
output = 0x55ac33bd0080
(gdb) print *output
$2 = {oguri = 0x7ffe2f72ba90, link = {prev = 0x55ac33bc4bd8, next = 0x55ac33bc4bd8}, 
  name = 0x55ac33bcff70 "DP-3", output = 0x55ac33bd0030, surface = 0x55ac33bd00e0, 
  layer_surface = 0x55ac33bd0900, width = 2560, height = 1440, scale = 1, 
  cached_frames = 0, buffer_ring = {prev = 0x0, next = 0x0}}
```
I don't know exactly when this occurred (just noticed it in coredumpctl), but I believe it was immediately after oguri was started by sway (as `swaybg_command`) when I connected the output.

Not sure how this is happening, as list initialization is the very first thing that `oguri_output_create` does.

**Comment by vilhalmer** [comment]
Outputs will now not assign themselves to an animation until the layer surface is configured. Going to assume this is fixed.
